// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAfBX5lwW5Hn0__YTekFNGZ8uBDcv1pA',
    appId: '1:444461504285:web:a8fb3b94229fbd379473f4',
    messagingSenderId: '444461504285',
    projectId: 'learning-app-6d5eb',
    authDomain: 'learning-app-6d5eb.firebaseapp.com',
    storageBucket: 'learning-app-6d5eb.firebasestorage.app',
    measurementId: 'G-4FK0HKJGQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNelu1T7SDCchTcFoDNom12XO8A_QVAME',
    appId: '1:444461504285:android:98f7c7effb8c6d6f9473f4',
    messagingSenderId: '444461504285',
    projectId: 'learning-app-6d5eb',
    storageBucket: 'learning-app-6d5eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCtuMziBMkF7xJl1Wg_U_EdPBbHzUYoyY',
    appId: '1:444461504285:ios:c1fff67140bf208c9473f4',
    messagingSenderId: '444461504285',
    projectId: 'learning-app-6d5eb',
    storageBucket: 'learning-app-6d5eb.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCtuMziBMkF7xJl1Wg_U_EdPBbHzUYoyY',
    appId: '1:444461504285:ios:c1fff67140bf208c9473f4',
    messagingSenderId: '444461504285',
    projectId: 'learning-app-6d5eb',
    storageBucket: 'learning-app-6d5eb.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAfBX5lwW5Hn0__YTekFNGZ8uBDcv1pA',
    appId: '1:444461504285:web:ef7b373f5cecfb889473f4',
    messagingSenderId: '444461504285',
    projectId: 'learning-app-6d5eb',
    authDomain: 'learning-app-6d5eb.firebaseapp.com',
    storageBucket: 'learning-app-6d5eb.firebasestorage.app',
    measurementId: 'G-CR4L2HY6KQ',
  );
}
